# Generated by Django 4.1 on 2022-08-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imag',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
